2020-11-23 13:55:15,378 - BetterDealUI - INFO - Add search: fds : 555
2020-11-23 14:02:46,075 - BetterDealUI - INFO - Add search: Coche / link.com
2020-11-23 14:02:46,259 - BetterDealUI - INFO - Refresh searches 
2020-11-23 14:03:35,022 - BetterDealUI - INFO - Remove search called
2020-11-23 14:12:35,721 - BetterDealUI - INFO - Remove search called
2020-11-23 14:17:21,458 - BetterDealUI - INFO - Remove search called on ('Mini Cooper', 'https://www.kijiji.ca/b-cars-trucks/ottawa-gatineau-area/mini-cooper/k0c174l1700184')
2020-11-23 14:17:21,599 - BetterDealUI - INFO - Refresh searches 
2020-11-23 14:17:39,870 - BetterDealUI - INFO - Remove search called on ('Chevrolet Camaro', 'https://www.kijiji.ca/b-cars-trucks/ottawa-gatineau-area/honda-civic/k0c174l1700184')
2020-11-23 14:17:40,060 - BetterDealUI - INFO - Refresh searches 
2020-11-23 14:18:05,196 - BetterDealUI - INFO - Add search: Mini Cooper / https://www.kijiji.ca/b-cars-trucks/ottawa-gatineau-area/mini-cooper/k0c174l1700184
2020-11-23 14:18:06,201 - BetterDealUI - INFO - Refresh searches 
2020-11-23 14:18:23,698 - BetterDealUI - INFO - Add search: Chevrolet Camaro / https://www.kijiji.ca/b-cars-trucks/ottawa-gatineau-area/honda-civic/k0c174l1700184
2020-11-23 14:18:23,839 - BetterDealUI - INFO - Refresh searches 
2020-11-23 14:22:52,761 - BetterDealUI - INFO - Remove search called on ('Coche', 'link.com')
2020-11-23 14:22:52,914 - BetterDealUI - INFO - Refresh searches 
2020-11-23 15:14:08,783 - BetterDealUI - INFO - Refresh searches 
2020-11-23 15:14:12,894 - BetterDealUI - INFO - Refresh searches 
2020-11-23 15:41:01,667 - BetterDealUI - INFO - Cars were downloaded to 'cars.csv'
2020-11-23 15:47:38,601 - BetterDealUI - INFO - Cars were downloaded to 'cars.csv'
2020-11-23 17:39:38,441 - BetterDealUI - INFO - Cars were downloaded to 'cars.csv'
2020-11-23 17:44:07,737 - BetterDealUI - INFO - Add search: Pony / lelink.com
2020-11-24 18:22:26,320 - BetterDealUI - INFO - Refresh searches 
2020-11-24 18:22:32,015 - BetterDealUI - INFO - Refresh searches 
2020-11-24 18:23:13,872 - BetterDealUI - INFO - Refresh searches 
2020-11-24 18:23:16,143 - BetterDealUI - INFO - Refresh searches 
2020-11-24 18:23:47,935 - BetterDealUI - INFO - Refresh searches 
2020-11-24 18:23:47,938 - BetterDealUI - ERROR - Error retrieving searches: 
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\util\connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\urit\Anaconda3\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
    conn = self._new_conn()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002335EE53908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='betterdeals-de427.firebaseio.com', port=443): Max retries exceeded with url: /Searches.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002335EE53908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 33, in retrieveSearches
    searches_json = db.child('Searches').get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 263, in get
    request_object = self.requests.get(request_ref, headers=headers)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='betterdeals-de427.firebaseio.com', port=443): Max retries exceeded with url: /Searches.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002335EE53908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2020-11-24 18:24:30,216 - BetterDealUI - INFO - Refresh searches 
2020-11-24 18:27:41,498 - BetterDealUI - INFO - Cars were downloaded to C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI/cars.csv
2020-11-24 20:16:19,090 - BetterDealUI - INFO - Filter cars called with values: ['', 'lol', 'lol']
2020-11-24 20:16:19,104 - BetterDealUI - ERROR - Unable to parse price value to float.
Traceback (most recent call last):
  File "C:/Users/urit/OneDrive/Escritorio/uOttawa/5th year/BetterDealUI/main.py", line 319, in on_bt_filter_cars_click
    float(self.edit_price_from.text())
ValueError: could not convert string to float: 'lol'
2020-11-24 20:16:27,479 - BetterDealUI - INFO - Filter cars called with values: ['', '50', '']
2020-11-24 20:16:38,241 - BetterDealUI - INFO - Filter cars called with values: ['', 'POny', '']
2020-11-24 20:16:50,292 - BetterDealUI - INFO - Filter cars called with values: ['Yoooo', '', '']
2020-11-24 20:16:52,772 - BetterDealUI - INFO - Filter cars called with values: ['Yoooo', '', '']
2020-11-24 20:16:57,034 - BetterDealUI - INFO - Filter cars called with values: ['', '', '']
2020-11-24 20:20:05,460 - BetterDealUI - INFO - Filter cars called with values: ['', '', '']
2020-11-24 20:23:06,280 - BetterDealUI - INFO - Filter cars called with values: ['', '', '']
2020-11-24 20:23:26,531 - BetterDealUI - INFO - Filter cars called with values: ['', '', '']
2020-11-24 20:23:33,864 - BetterDealUI - INFO - Filter cars called with values: ['Yooo', '', '']
2020-11-24 20:23:44,615 - BetterDealUI - INFO - Filter cars called with values: ['Yooo', '55', '']
2020-11-24 20:23:56,868 - BetterDealUI - INFO - Filter cars called with values: ['Yooo', '', '44']
2020-11-24 20:24:05,086 - BetterDealUI - INFO - Filter cars called with values: ['Yooo', '55', '44']
2020-11-24 20:24:08,746 - BetterDealUI - INFO - Filter cars called with values: ['Yooo', '55', '44']
2020-11-24 20:26:26,223 - BetterDealUI - ERROR - Failed to download cars: 
Traceback (most recent call last):
  File "C:/Users/urit/OneDrive/Escritorio/uOttawa/5th year/BetterDealUI/main.py", line 360, in on_bt_download_cars
    with open('cars.csv', 'w', newline='') as file:
PermissionError: [Errno 13] Permission denied: 'cars.csv'
2020-11-24 20:26:38,998 - BetterDealUI - ERROR - Failed to download cars: 
Traceback (most recent call last):
  File "C:/Users/urit/OneDrive/Escritorio/uOttawa/5th year/BetterDealUI/main.py", line 366, in on_bt_download_cars
    cars[i][1].encode('utf-8').decode('utf-8'),  # price
AttributeError: 'float' object has no attribute 'encode'
2020-11-24 20:30:27,102 - BetterDealUI - INFO - Filter cars called with values: ['', '', '']
2020-11-25 00:58:21,435 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 56, in retrieveCars
    if filters[0] != "" and filters[1] != "" and filters[2] != "":
IndexError: list index out of range
2020-11-25 01:07:36,041 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 58, in retrieveCars
    if filters[0] != "" and filters[1] != "" and filters[2] != "":
IndexError: list index out of range
2020-11-25 01:29:55,236 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '']
2020-11-25 01:30:08,836 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '55']
2020-11-25 01:31:19,591 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '']
2020-11-25 01:31:25,310 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', 'dd']
2020-11-25 01:31:35,993 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '2020*88*99']
2020-11-25 01:31:35,994 - BetterDealUI - ERROR - Invalid date format.
Traceback (most recent call last):
  File "C:/Users/urit/OneDrive/Escritorio/uOttawa/5th year/BetterDealUI/main.py", line 352, in on_bt_filter_cars_click
    raise Exception
Exception
2020-11-25 01:31:47,256 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '2020/12/11']
2020-11-25 01:31:57,462 - BetterDealUI - INFO - Filter cars called with values: ['', '55', '', '2020/12/11']
2020-11-25 01:32:51,725 - BetterDealUI - INFO - Filter cars called with values: ['', '55', '', '2020/12/11']
2020-11-25 01:33:05,063 - BetterDealUI - INFO - Filter cars called with values: ['', '55', '77', '2020/12/11']
2020-11-25 11:08:42,168 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?limitToFirst=200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 96, in retrieveCars
    cars_json = db.child("Cars").limit_to_first(MAX_QUERY_SIZE).get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?limitToFirst=200] {
  "error" : "orderBy must be defined when other query parameters are defined"
}

2020-11-25 11:09:46,702 - BetterDealUI - INFO - Filter cars called with values: ['', '200', '3000', '']
2020-11-25 11:09:46,894 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Price%2522&startAt=200&endAt=3000&limitToFirst=200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 86, in retrieveCars
    end_at(int(price_to)).limit_to_first(MAX_QUERY_SIZE).get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Price%2522&startAt=200&endAt=3000&limitToFirst=200] {
  "error" : "orderBy must be a valid JSON encoded path"
}

2020-11-25 11:39:42,090 - BetterDealUI - INFO - Filter cars called with values: ['', '200', '3000', '']
2020-11-25 11:39:42,353 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Price%2522&startAt=200&endAt=3000&limitToFirst=200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 86, in retrieveCars
    end_at(int(price_to)).limit_to_first(MAX_QUERY_SIZE).get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Price%2522&startAt=200&endAt=3000&limitToFirst=200] {
  "error" : "orderBy must be a valid JSON encoded path"
}

2020-11-25 11:41:54,554 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '2020/11/24']
2020-11-25 11:41:54,798 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Date%2522&equalTo=%25222020%2F11%2F24%2522&limitToFirst=200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 92, in retrieveCars
    limit_to_first(MAX_QUERY_SIZE).get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Date%2522&equalTo=%25222020%2F11%2F24%2522&limitToFirst=200] {
  "error" : "orderBy must be a valid JSON encoded path"
}

2020-11-25 11:47:01,539 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?limitToFirst=%2522200%2522

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 98, in retrieveCars
    cars_json = db.child("Cars").limit_to_first(str(MAX_QUERY_SIZE)).get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?limitToFirst=%2522200%2522] {
  "error" : "orderBy must be defined when other query parameters are defined"
}

2020-11-25 11:47:34,553 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '2020/11/24']
2020-11-25 11:47:34,728 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Date%2522&equalTo=%2522%25222020%2F11%2F24%2522%2522

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 93, in retrieveCars
    cars_json = db.child("Cars").order_by_child("Date").equal_to('"'+date+'"').get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Date%2522&equalTo=%2522%25222020%2F11%2F24%2522%2522] {
  "error" : "orderBy must be a valid JSON encoded path"
}

2020-11-25 12:02:37,897 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?limitToFirst=%2522200%2522

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 98, in retrieveCars
    cars_json = db.child("Cars").limit_to_first(str(MAX_QUERY_SIZE)).get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?limitToFirst=%2522200%2522] {
  "error" : "orderBy must be defined when other query parameters are defined"
}

2020-11-25 12:02:48,260 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '2020/11/24']
2020-11-25 12:02:48,465 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Date%2522&equalTo=%2522%25222020%2F11%2F24%2522%2522

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 93, in retrieveCars
    cars_json = db.child("Cars").order_by_child("Date").equal_to('"'+date+'"').get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%2522Date%2522&equalTo=%2522%25222020%2F11%2F24%2522%2522] {
  "error" : "orderBy must be a valid JSON encoded path"
}

2020-11-25 12:07:20,687 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 503, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?limitToFirst=200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 98, in retrieveCars
    cars_json = db.child("Cars").limit_to_first(MAX_QUERY_SIZE).get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 281, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 507, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?limitToFirst=200] {
  "error" : "orderBy must be defined when other query parameters are defined"
}

2020-11-25 12:07:35,269 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '2020/11/24']
2020-11-25 12:08:02,538 - BetterDealUI - INFO - Filter cars called with values: ['', '1000', '3500', '2020/11/24']
2020-11-25 12:08:02,714 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 503, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%22Date%22&startAt=1000&endAt=3500&equalTo=%222020%2F11%2F24%22&limitToFirst=200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 80, in retrieveCars
    end_at(int(price_to)).order_by_child("Date").equal_to(date).limit_to_first(MAX_QUERY_SIZE).get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 281, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 507, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%22Date%22&startAt=1000&endAt=3500&equalTo=%222020%2F11%2F24%22&limitToFirst=200] {
  "error" : "equalTo cannot be specified in addition to startAt or endAt"
}

2020-11-25 12:08:10,247 - BetterDealUI - INFO - Filter cars called with values: ['', '1000', '5000', '2020/11/24']
2020-11-25 12:08:10,424 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 503, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%22Date%22&startAt=1000&endAt=5000&equalTo=%222020%2F11%2F24%22&limitToFirst=200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 80, in retrieveCars
    end_at(int(price_to)).order_by_child("Date").equal_to(date).limit_to_first(MAX_QUERY_SIZE).get()
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 281, in get
    raise_detailed_error(request_object)
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\venv\lib\site-packages\pyrebase\pyrebase.py", line 507, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://betterdeals-de427.firebaseio.com/Cars.json?orderBy=%22Date%22&startAt=1000&endAt=5000&equalTo=%222020%2F11%2F24%22&limitToFirst=200] {
  "error" : "equalTo cannot be specified in addition to startAt or endAt"
}

2020-11-25 12:08:53,916 - BetterDealUI - INFO - Filter cars called with values: ['', '1000', '5000', '']
2020-11-25 12:47:06,014 - BetterDealUI - INFO - Filter cars called with values: ['mini cooper', '', '', '']
2020-11-25 12:47:53,054 - BetterDealUI - INFO - Filter cars called with values: ['mini cooper', '3000', '6000', '']
2020-11-25 12:48:07,215 - BetterDealUI - INFO - Filter cars called with values: ['', '3000', '6000', '']
2020-11-25 12:48:19,570 - BetterDealUI - INFO - Filter cars called with values: ['', '3000', '6000', '2020/11/24']
2020-11-25 12:48:34,583 - BetterDealUI - INFO - Filter cars called with values: ['mini cooper 2010', '3000', '6000', '2020/11/24']
2020-11-25 12:48:44,157 - BetterDealUI - INFO - Filter cars called with values: ['mini cooper 2010', '3000', '', '2020/11/24']
2020-11-25 12:53:35,338 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 88, in retrieveCars
    if keyword != "":  # if we must filter by keyword
UnboundLocalError: local variable 'keyword' referenced before assignment
2020-11-25 12:53:35,341 - BetterDealUI - INFO - List of cars was empty or an error occurred. No file has been created.
2020-11-25 12:58:42,802 - BetterDealUI - INFO - Filter cars called with values: ['', '55', '66', '']
2020-11-25 12:58:43,137 - BetterDealUI - ERROR - Error retrieving cars from the database:
Traceback (most recent call last):
  File "C:\Users\urit\OneDrive\Escritorio\uOttawa\5th year\BetterDealUI\database.py", line 84, in retrieveCars
    for car in cars_json.each():
TypeError: 'NoneType' object is not iterable
2020-11-25 13:38:50,304 - BetterDealUI - WARNING - ALL CARS TO BE DELETED FROM DB
2020-11-25 13:38:50,305 - BetterDealUI - INFO - Filter cars called with values: ['', '', '', '']
2020-11-25 13:40:24,290 - BetterDealUI - WARNING - ALL CARS TO BE DELETED FROM DB
2020-11-25 13:40:27,826 - BetterDealUI - WARNING - ALL CARS TO BE DELETED FROM DB
2020-11-25 13:40:30,722 - BetterDealUI - WARNING - ALL CARS TO BE DELETED FROM DB
2020-11-25 13:40:34,294 - BetterDealUI - WARNING - ALL CARS TO BE DELETED FROM DB
2020-11-25 13:40:46,835 - BetterDealUI - INFO - Filter cars called with values: ['sedan', '', '', '']
2020-11-25 13:40:59,543 - BetterDealUI - INFO - Add search: pony / link
2020-11-25 13:40:59,750 - BetterDealUI - INFO - Refresh searches 
2020-11-25 13:41:05,288 - BetterDealUI - INFO - Remove search called on ('pony', 'link')
2020-11-25 13:41:05,468 - BetterDealUI - INFO - Refresh searches 
